// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA80eZEAboM-fp-BGpl5OUDyb_m3e2il6E',
    appId: '1:1034699988850:web:a0c50d54eae4c0a4da47eb',
    messagingSenderId: '1034699988850',
    projectId: 'mindbox-b839e',
    authDomain: 'mindbox-b839e.firebaseapp.com',
    storageBucket: 'mindbox-b839e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5kyORjMFjgbmCNqEKeqKT_NwqSP-d2-M',
    appId: '1:1034699988850:android:16dcf17f4f6dce4fda47eb',
    messagingSenderId: '1034699988850',
    projectId: 'mindbox-b839e',
    storageBucket: 'mindbox-b839e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABNI66WZOz-D9LDLyF-o4kK4KbH82RlrA',
    appId: '1:1034699988850:ios:7b444fab922eb67fda47eb',
    messagingSenderId: '1034699988850',
    projectId: 'mindbox-b839e',
    storageBucket: 'mindbox-b839e.firebasestorage.app',
    androidClientId: '1034699988850-8pbgpi90jal38u9dhffrm42d71v9d0vh.apps.googleusercontent.com',
    iosClientId: '1034699988850-fgugb8apf65kbc62jm8hptsfvgi9ou5j.apps.googleusercontent.com',
    iosBundleId: 'mindbox.devninja.xyz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABNI66WZOz-D9LDLyF-o4kK4KbH82RlrA',
    appId: '1:1034699988850:ios:7b444fab922eb67fda47eb',
    messagingSenderId: '1034699988850',
    projectId: 'mindbox-b839e',
    storageBucket: 'mindbox-b839e.firebasestorage.app',
    androidClientId: '1034699988850-8pbgpi90jal38u9dhffrm42d71v9d0vh.apps.googleusercontent.com',
    iosClientId: '1034699988850-fgugb8apf65kbc62jm8hptsfvgi9ou5j.apps.googleusercontent.com',
    iosBundleId: 'mindbox.devninja.xyz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA80eZEAboM-fp-BGpl5OUDyb_m3e2il6E',
    appId: '1:1034699988850:web:32fd2ba6241394b6da47eb',
    messagingSenderId: '1034699988850',
    projectId: 'mindbox-b839e',
    authDomain: 'mindbox-b839e.firebaseapp.com',
    storageBucket: 'mindbox-b839e.firebasestorage.app',
  );

}